ha_ws_url: ws://192.168.1.71:8123/api/websocket
ha_rest_url: http://192.168.1.71:8123/api
#ha_url: wss://home.trevorandcameron.com/api/websocket
ws_reconnect_min_interval_ms: 100
ws_reconnect_max_interval_ms: 60000
